const DLF_HEADER_SIZE = 8520;

const FTS_HEADER_SIZE = 280;
const FTS_UNIQUE_HEADER_SIZE = 768;

const LLF_HEADER_SIZE = 0;

const FTL_HEADER_SIZE = -1;

module.exports = {
  DLF_HEADER_SIZE,
  FTS_HEADER_SIZE,
  FTS_UNIQUE_HEADER_SIZE,
  LLF_HEADER_SIZE,
  FTL_HEADER_SIZE,
};
